### ISSUE TITLE
Adding User Assigned Identity to group fails when the object_id is not known yet

### ISSUE THREAD

**Issue by blinq-kim** [blinqas/station#69]
This happens because sets are calculated at plan time, and Terraform is unable to construct the set from values that do not yet exist.

Possible fix is changing from set to list and using `toset()` in the group_member.tf file.

Testing `depends_on` first.

Error message:

The "for_each" set includes values derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this resource. When working with unknown values in for_each, it's better to use a map value where the keys are defined statically in your configuration and where only the values contain apply-time results. Alternatively, you could use the -target planning option to first apply only the resources that the for_each value depends on, and then apply a second time to fully converge.

**Comment by ghost** [comment]
`depends_on` did not solve the issue
