### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by kimfy** [blinqas/station#84]
Make the README more understandable.

- How does Station work?
- Station uses X to solve what, exactly?

Station depends on Terraform Cloud to achieve end-to-end automation of environment creation. Station creates Terraform Cloud workspaces per module initialization, configures Version Control triggers to automatically deploy when your git repository is updated. You choose what to trigger a deployment on; branch or tag.

**Comment by SanderBlom** [comment]
It could also be beneficial to create reference architecture where we explain with some text and diagrams on how station could be utilized.
